### ISSUE TITLE
关于使用方法

### ISSUE THREAD

**Issue by adsznzhang** [xiaolei0517/RLMPubkey#1]
请问比如同一个软件不同的模块，要怎么生成签名呢？有人一同研究RLM吗？我这有SDK，求指导啊。还有就是手动替换public key的问题。感谢！感谢！感谢！

**Comment by adsznzhang** [comment]
通过阅读SDK，了解了。。。如果有人想要学习。可以问我要SDK。。。11.3版本的。 谁有新版本的求共享啊！

**Comment by laonan007** [comment]
[adsznzhang](https://github.com/adsznzhang)
可以分享一份rlm 13或14的sdk吗？
